apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-player
  labels:
    app: video-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-player
  template:
    metadata:
      labels:
        app: video-player
    spec:
      containers:
      - name: video-player
        image: tolerantleechacr.azurecr.io/video-player:linux
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "tolerantleechsa"
        - name: AZURE_STORAGE_CONTAINER_NAME
          value: "data"
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: storage-connection-string
              key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: video-player-service
spec:
  selector:
    app: video-player
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
