apiVersion: v1
kind: Secret
metadata:
  name: azure-ad-credentials
type: Opaque
stringData:
  client-id: "${AZURE_AD_CLIENT_ID}"
  client-secret: "${AZURE_AD_CLIENT_SECRET}"
  tenant-id: "${AZURE_AD_TENANT_ID}"
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-connection-string
type: Opaque
stringData:
  connection-string: "${STORAGE_CONNECTION_STRING}"
